name: Run tests

# триггер
on: [ push, workflow_dispatch ]

jobs: # джобы, аналог этапов
  run-tests:
    name: Set up services (review apps) and run tests
    runs-on: ubuntu-latest    # на какой ранере (агенте) мы хотим выполнять тесты
    steps: # шаги конкретной job
      - name: Checkout repository   # шаг 1 - копируем файлы репозитория внутрь CI агента
        uses: actions/checkout@v4

      - name: Set up JDK            # шаг 2 - устанавливаем JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven repository # шаг 3 - создаем cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up services        # шаг 4 - запускаем restart_docker.sh
        run: cd infra/docker_compose && bash restart_docker.sh && cd ../..

      - name: Give execute permission to mvnw  # шаг 5- устанавливаем права доступа
        run: chmod +x mvnw

      - name: Run tests              # шаг 6- запуск тестов
        continue-on-error: true
        env:
          APIBASEURL: http://localhost:4111
          UIBASEURL: http://nginx:80
          UIREMOTE: http://localhost:4444/wd/hub
          APIVERSION: /api/v1
        run: |
          echo "=== Environment Variables ==="
          echo "UIBASEURL: $UIBASEURL"
          echo "APIBASEURL: $APIBASEURL"
          echo "UIREMOTE: $UIREMOTE"
          echo "=== === ==="
          ./mvnw clean test

