name: Run tests

# триггер
on: [ push, workflow_dispatch ]

jobs: # джобы, аналог этапов
  run-tests:
    name: Set up services (review apps) and run tests
    runs-on: ubuntu-latest    # на какой ранере (агенте) мы хотим выполнять тесты
    steps: # шаги конкретной job
      - name: Checkout repository # копируем файлы репозитория внутрь CI агента
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up services
        run: cd infra/docker_compose && bash restart_docker.sh && cd ../..

      - name: Give execute permission to mvnw
        run: chmod +x mvnw

      - name: Run tests
        env:
          APIBASEURL: http://localhost:4111
          UIBASEURL: http://nginx:80
          UIREMOTE: http://localhost:4444/wd/hub
          APIVERSION: /api/v1
          continue-on-error: true
        run: |
          echo "=== Environment Variables ==="
          echo "UIBASEURL: $UIBASEURL"
          echo "APIBASEURL: $APIBASEURL"
          echo "=== System Properties ==="
          ./mvnw clean test

      - name: Проверка доступности сервисов
        run: |
         echo "1. Проверяем nginx на localhost:80"
         curl -f http://localhost || echo "NGINX не доступен"
    
         echo ""
         echo "2. Проверяем frontend через nginx"
         curl -f http://localhost/api/health || echo "Через nginx не работает"
    
         echo ""
         echo "3. Проверяем frontend напрямую из сети"
         docker run --rm --network nbank-network curlimages/curl \
         curl -f http://frontend:80 || echo "Frontend напрямую не доступен"  
